### ISSUE TITLE
cxxtest missing?

### ISSUE THREAD

**Issue by queisser** [Aquaveo/xmsinterp#14]
Trying a fresh build of xmsinterp for MSVC 2015 or 2017. I cannot seem to find cxxtest

from conanfile.py: 
  `build_requires = "cxxtest/4.4@aquaveo/stable"`

I'm totally new to conan but if I'm not mistaken there's no cxxtest at aquaveo and I can't seem to find any other way to make conan happy.

**Comment by Tsubashi** [comment]
Aquaveo maintains their own conan remote at `https://conan.aquaveo.com`
 run `conan remote add aquaveo https://conan.aquaveo.com` to add it.
