### ISSUE TITLE
Interpolating large datasets

### ISSUE THREAD

**Issue by kcpevey** [Aquaveo/xmsinterp#18]
I'm attempting to interpolate an 8M point dataset onto a 8M node mesh using the python xmsinterp tools (idw). When I do this inside of jupyter lab, I get the error:  

```
IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)
```
   
I'm running Jupyter 4.4.0 for dependency reasons. From google, I found that the following adjustment fixed this issue for many people:  
`jupyter notebook --NotebookApp.iopub_data_rate_limit=1.0e10`
  
However, when I used the above to launch a notebook and attempt my interpolation, it crashed the browser page of the notebook and the browser page of my root jupyter.   
  
Has anyone tested files of this size? Is there another workaround for this?

**Comment by Tsubashi** [comment]
It looks to me like this problem is jupyter specific. The c++ library which the python wraps has been used successfully against datasets of this size. 

With that said, there may be ways to work around it. Do you have a project you could share to reproduce the issue?

**Comment by kcpevey** [comment]
The first time I tried to implement  
`jupyter notebook --NotebookApp.iopub_data_rate_limit=1.0e10`  
  
I applied it incorrectly in the jupyter config file. Once I corrected it to properly reflect the above, I no longer receive this error.
